Testing the new install script functionality on Linux

diff --git a/.github/workflows/check_install_script.yaml b/.github/workflows/check_install_script.yaml
--- a/.github/workflows/check_install_script.yaml
+++ b/.github/workflows/check_install_script.yaml
@@ -154,6 +154,43 @@ jobs:
               test ! -f $element
           done
 
+          ###
+          # testing the install from TIPI_INSTALL_SOURCE path
+
+          rm $(which tipi)
+
+          export INSTALL_SRC_TEST_OUTFILE=tipiv0.0.30.zip
+          wget https://github.com/tipi-build/cli/releases/download/v0.0.30/tipi-v0.0.30-linux-x86_64.zip -O $INSTALL_SRC_TEST_OUTFILE
+
+          export TIPI_INSTALL_SOURCE=$(realpath file://$INSTALL_SRC_TEST_OUTFILE)
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)" | grep "$TIPI_INSTALL_SOURCE"
+
+          if [ $? -ne 0 ]; then
+            exit 1
+          fi
+
+          tipi --help --dont-upgrade | grep "v0.0.30"
+          if [ $? -ne 0 ]; then
+            exit 1
+          fi
+
+          ###
+          # negative test / install from TIPI_INSTALL_SOURCE should fail if path doesn't exist
+          rm $(which tipi)
+
+          export TIPI_INSTALL_SOURCE=/tmp/rAnDoMfiLe.noknownext
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
+          if [ $? -ne 1 ]; then
+            exit 1
+          fi
+
+          which tipi
+          if [ $? -ne 1 ]; then
+            exit 1
+          fi
+
+
+
   install-windows-powershell-full:
     name: install-windows-powershell-full
     runs-on: windows-latest
