Fixed and improved (now testing install location and if tipi has been correctly added to the path) test for windows installs and added TIPI_INSTALL_SYSTEM test case

diff --git a/.github/workflows/check_install_script.yaml b/.github/workflows/check_install_script.yaml
--- a/.github/workflows/check_install_script.yaml
+++ b/.github/workflows/check_install_script.yaml
@@ -189,6 +189,10 @@ jobs:
 
           $success = $true
 
+          # this checks that tipi is on PATH and that it's where we expect it to be.
+          $expected_install_folder = Join-Path -Path ([Environment]::GetFolderPath('LocalApplicationData')) -ChildPath "\tipi"
+          $success = (get-command tipi).Path -eq $expected_install_folder
+
           foreach ( $testPath in $pathsToTest )
           {
                 if (!(Test-Path $testPath -PathType leaf)) { 
@@ -199,6 +203,65 @@ jobs:
 
           if(!$success) { exit 1; }
         shell: powershell
+
+  system-install-windows-powershell-light:
+    name: install-windows-powershell-light
+    runs-on: windows-latest
+    steps:
+      - name: test_install_on_windows_powershell
+        run: |
+          # force system install to "C:\ProgramData\tipi\tipi.exe"
+          $env:TIPI_INSTALL_SYSTEM="True"
+
+          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
+            $script_source = $env:GITHUB_HEAD_REF.replace('refs/heads/', '')
+          } else {
+            $script_source = $env:GITHUB_REF.replace('refs/heads/', '')
+          }
+          . { iwr -useb https://raw.githubusercontent.com/tipi-build/cli/$script_source/install/install_for_windows.ps1 } | iex 
+          if (!($?)) {exit 1}
+          # Test install succeeeded 
+
+          $pathsToTest = @(
+            "C:\\ProgramData\\tipi\\tipi.exe"   
+            "C:\\.tipi\\environments\\*\\xcode.cmake" 
+            "C:\\.tipi\\openssh\\*\\ssh.exe"
+            "C:\\.tipi\\python\\*\\python.exe"  
+            "C:\\.tipi\\file-sync\\*\\pysearpc\\client.py"  
+          )
+
+          $success = $true
+          
+          # this checks that tipi is on PATH and that it's where we expect it to be.
+          $expected_install_folder = Join-Path -Path ([Environment]::GetFolderPath('LocalApplicationData')) -ChildPath "\tipi"
+          $success = (get-command tipi).Path -eq $expected_install_folder
+
+          foreach ( $testPath in $pathsToTest )
+          {
+                if (!(Test-Path $testPath -PathType leaf)) { 
+                    echo "[FAIL] Expected <$testPath> was not found in installation."
+                    $success = $false; 
+                }
+          }
+
+          # test just a few things in the light install to make sure they are *NOT* present
+          $pathsToTest_negative = @(
+              "C:\\.tipi\\clang\\*\\bin\\clang.exe"  
+              "C:\\.tipi\\cmake\\*\\bin\\cmake.exe"  
+              "C:\\.tipi\\emsdk\\*\\emsdk.bat"              
+              "C:\\.tipi\\go\\*\\bin\\go.exe"  
+              "C:\\.tipi\\jdk\\*\\bin\\jar.exe"              
+          )
+          foreach ( $testPath in $pathsToTest_negative )
+          {
+              if (Test-Path $testPath -PathType leaf) {
+                  echo "[FAIL] Unexpected <$testPath> was found in installation."
+                  $success = $false;
+              }
+          }
+          
+          if(!$success) { exit 1; }
+        shell: powershell  
 
   install-windows-powershell-light:
     name: install-windows-powershell-light
@@ -224,6 +287,10 @@ jobs:
           )
 
           $success = $true
+
+          # this checks that tipi is on PATH and that it's where we expect it to be.
+          $expected_install_folder = "C:\\ProgramData\\tipi\\tipi.exe"   
+          $success = (get-command tipi).Path -eq $expected_install_folder
 
           foreach ( $testPath in $pathsToTest )
           {
